import os
import logging
from dj_secure_settings.loader import load_secure_settings
from pathlib import Path


"""
Django settings for {{ project_name }} project.
Generated by 'django-admin startproject' using Django {{ django_version }} of TLT template.
For more information on this file, see
https://docs.djangoproject.com/en/{{ docs_version }}/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/
"""

SECURE_SETTINGS = load_secure_settings()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# NOTE: Since we have a settings module, we have to go one more directory up to get to
# the project root
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Application definition

INSTALLED_APPS = [
    #  'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    "allow_cidr.middleware.AllowCIDRMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Authentication

# Django defaults are below, but will need to be customized if using something
# other than the built-in Django auth, such as PIN, LTI, etc.
# AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend',)
# LOGIN_URL = '/accounts/login'

ROOT_URLCONF = '{{ project_name }}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '{{ project_name }}.wsgi.application'

# DatabaseSESSION_COOKIE_SAMESITE = "None"  # should be set as 'None' for Django >= 3.1
SESSION_COOKIE_SECURE = True  # should be True in case of HTTPS usage (production)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_COOKIE_SAMESITE = "None"  # should be set as 'None' for Django >= 3.1
CSRF_COOKIE_SECURE = True  # should be True in case of HTTPS usage (production)

# https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': SECURE_SETTINGS.get('db_default_name', '{{ project_name }}'),
        'USER': SECURE_SETTINGS.get('db_default_user', 'postgres'),
        'PASSWORD': SECURE_SETTINGS.get('db_default_password'),
        'HOST': SECURE_SETTINGS.get('db_default_host', '127.0.0.1'),
        'PORT': SECURE_SETTINGS.get('db_default_port', 5432),  # Default postgres port
    },
}

# Sessions
# https://docs.djangoproject.com/en/{{ docs_version }}/topics/http/sessions/#module-django.contrib.sessions

# Store sessions in default cache defined below
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# NOTE: This setting only affects the session cookie, not the expiration of the session
# being stored in the cache.  The session keys will expire according to the value of
# SESSION_COOKIE_AGE (https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/#session-cookie-age),
# which defaults to 2 weeks.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Cache
# https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/#std:setting-CACHES

REDIS_HOST = SECURE_SETTINGS.get('redis_host', '127.0.0.1')
REDIS_PORT = SECURE_SETTINGS.get('redis_port', 6379)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': "redis://%s:%s/0" % (REDIS_HOST, REDIS_PORT),
        'KEY_PREFIX': '{{ project_name }}',  # Provide a unique value for shared cache
        # See following for default timeout (5 minutes as of 1.7):
        # https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/#std:setting-CACHES-TIMEOUT
        'TIMEOUT': SECURE_SETTINGS.get('default_cache_timeout_secs', 300),
    },
}

# Internationalization
# https://docs.djangoproject.com/en/{{ docs_version }}/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
# A boolean that specifies whether Django's translation system should be enabled. This provides
# an easy way to turn it off, for performance. If this is set to False, Django will make some
# optimizations so as not to load the translation machinery.
USE_I18N = False

# A boolean that specifies if localized formatting of data will be enabled by default or not.
# If this is set to True, e.g. Django will display numbers and dates using the format of the
# current locale.  NOTE: this would only really come into play if your locale was outside of the
# US
USE_L10N = False
# A boolean that specifies if datetimes will be timezone-aware by default or not. If this is set to
# True, Django will use timezone-aware datetimes internally. Otherwise, Django will use naive
# datetimes in local time.
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/{{ docs_version }}/howto/static-files/

# This directory is being ignored by git
STATIC_ROOT = os.path.normpath(os.path.join(BASE_DIR, 'http_static'))
STATIC_URL = '/static/'

# Logging
# https://docs.djangoproject.com/en/{{ docs_version }}/topics/logging/#configuring-logging


_DEFAULT_LOG_LEVEL = SECURE_SETTINGS.get("log_level", logging.DEBUG)
_JSON_LOG_FORMAT = "%(asctime)s %(created)f %(exc_info)s %(filename)s %(funcName)s %(levelname)s %(levelno)s %(name)s %(lineno)d %(module)s %(message)s %(pathname)s %(process)s"


class ContextFilter(logging.Filter):
    def __init__(self, **kwargs):
        self.extra = kwargs

    def filter(self, record):

        for k in self.extra:
            setattr(record, k, self.extra[k])

        return True


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"},
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": _JSON_LOG_FORMAT,
        },
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "filters": {
        "context": {
            "()": "ai_lti.settings.base.ContextFilter",
            "env": SECURE_SETTINGS.get("env_name"),
            "project": "ai_lti",
            "department": "uw",
        },
        "require_debug_false": {"()": "django.utils.log.RequireDebugFalse"},
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "default": {
            "class": "splunk_handler.SplunkHandler",
            "formatter": "json",
            "sourcetype": "json",
            "source": "django-ai_lti",
            "host": "http-inputs-harvard.splunkcloud.com",
            "port": "443",
            "index": "soc-isites",
            "token": SECURE_SETTINGS.get("splunk_token"),
            "level": _DEFAULT_LOG_LEVEL,
            "filters": ["context"],
        },
        "gunicorn": {
            "class": "splunk_handler.SplunkHandler",
            "formatter": "json",
            "sourcetype": "json",
            "source": "gunicorn-ai_lti",
            "host": "http-inputs-harvard.splunkcloud.com",
            "port": "443",
            "index": "soc-isites",
            "token": SECURE_SETTINGS.get("splunk_token"),
            "level": _DEFAULT_LOG_LEVEL,
            "filters": ["context"],
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["require_debug_true"],
        },
    },
    "loggers": {
        "root": {
            "handlers": ["default", "console"],
            "level": "WARNING",
            "propagate": True,
        },
        "django": {
            "handlers": ["default", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["default", "console"],
            "level": "ERROR",
            "propagate": False,
        },
        "{{ project_name }}": {
            "handlers": ["default", "console"],
            "level": _DEFAULT_LOG_LEVEL,
            "propagate": False,
        },
    },
}
# Other project specific settings
